In [ ]:
import sys

if not 'numpy' in sys.modules:
    !pip install numpy

import numpy as np

In [99]:
a = np.array(
      [
            [
                  [10, 15, 1]
                , [ 5, 10, 3]
                , [10,  5, 3]
            ]
          , [
                  [ 5, 25, 2]
                , [20, 20, 3]
                , [ 5, 15, 1]
            ]
      ]
)
np.array(sorted(a.reshape(-1, 3), key = lambda v: [v[0], v[1]])).reshape(a.shape)


array([[[ 5, 10,  3],
        [ 5, 15,  1],
        [ 5, 25,  2]],

       [[10,  5,  3],
        [10, 15,  1],
        [20, 20,  3]]])

In [65]:
np.rec.array(a)

rec.array([[[10, 15,  1],
            [ 5, 10,  3],
            [10,  5,  3]],

           [[ 5, 25,  2],
            [20, 20,  3],
            [ 5, 15,  1]]],
          dtype=int32)

In [11]:
field_names = ['y', 'x', 'classifier']

In [14]:
b = np.array([[[10, 15,  1],
        [ 5, 10,  3],
        [10,  5,  3]],

       [[ 5, 25,  2],
        [20, 20,  3],
        [ 5, 15,  1]]])

b

array([[[10, 15,  1],
        [ 5, 10,  3],
        [10,  5,  3]],

       [[ 5, 25,  2],
        [20, 20,  3],
        [ 5, 15,  1]]])

In [31]:
array_with_labels = np.array([[[(label, num) for i, num in enumerate(l2) for j, label in enumerate(field_names) if i == j] for l2 in l1] for l1 in b], dtype = [('yax'), (), ()]
array_with_labels

[[[('y', 10), ('x', 15), ('classifier', 1)],
  [('y', 5), ('x', 10), ('classifier', 3)],
  [('y', 10), ('x', 5), ('classifier', 3)]],
 [[('y', 5), ('x', 25), ('classifier', 2)],
  [('y', 20), ('x', 20), ('classifier', 3)],
  [('y', 5), ('x', 15), ('classifier', 1)]]]

In [25]:
np.sort(array_with_labels, order = ['y', 'x'])

ValueError: Cannot specify order when the array has no fields.

In [ ]:
[l2[0], l2[1], l2[2]]

In [9]:
np.sort(a, axis = 0)

array([[[ 5, 15,  1],
        [ 5, 10,  3],
        [ 5,  5,  1]],

       [[10, 25,  2],
        [20, 20,  3],
        [10, 15,  3]]])

In [4]:
import numpy as np
X = np.array([
    [5, 5, 4],
    [8, 1, 8],
    [0, 1, 5],
    [0, 3, 1],
    [6, 2, 5]
])

In [7]:
np.linalg.inv(np.matmul(X, X.T))

LinAlgError: Singular matrix

In [ ]:
def find_max_common_label_in_cluster(clustering, y, k):
    import numpy as np
    z = np.array([-1] * k)
    for i in set(clustering):
        y_indices = np.where(clustering == i)[0]
        y_take = np.take(y, y_indices)
        y_filtered = np.extract(y_take != -1, y_take)
        if y_filtered.size:
            counts = np.bincount(y_filtered)
            z[i] = np.argmax(counts)            
    return z

In [65]:
y = np.array([0,  0,  1,  0,  1,  0,  1,  0,  0,  0,  1,  0,  0,  1,  0,  0])

In [74]:
counts = np.bincount(y)
counts

array([11,  5], dtype=int64)

In [78]:
np.argmin(counts)

1

In [80]:
np.where(y == 1)[0]

array([ 2,  4,  6, 10, 13], dtype=int64)

In [58]:
from collections import Counter

In [59]:
ex2_demo_bags = [{'cat', 'dog', 'fish'},
                 {'red', 'blue'},
                 {'dog'},
                 {'one', 'two', 'dog', 'fish'}]


In [64]:

[Counter(list(st)) for st in ex2_demo_bags]

[Counter({'dog': 1, 'cat': 1, 'fish': 1}),
 Counter({'blue': 1, 'red': 1}),
 Counter({'dog': 1}),
 Counter({'dog': 1, 'two': 1, 'fish': 1, 'one': 1})]

In [55]:
ex1_demo_input = ["This is a phrase; this, too, is a phrase",
                  "But this is another sentence",
                  "Hark",
                  "Come what may    <-- save those spaces, but not these -->",
                  "What did you say",
                  "Split into 3 (even without a space)",
                  "Okie dokie"]

In [57]:
def clean(s):
    from re import finditer
    pattern = r"[a-z]+('[a-z])?[a-z]*"
    return [match.group(0) for match in finditer(pattern, s.lower())]

In [ ]:
def gen_bag_of_words(sents):
    assert isinstance(sents, list)
    for sentence in sents:
        for word in clean(sentence) if word not in STOPWORDS]
    
# Demo:
gen_bag_of_words(ex1_demo_input)

In [34]:
import re

In [33]:
ex0_demo_input = ["  This is a phrase; this, too, is a phrase. But this is another sentence.",
                  "Hark!",
                  "    ",
                  "Come what may    <-- save those spaces, but not these -->    ",
                  "What did you say?Split into 3 (even without a space)? Okie dokie."]

In [54]:
result = []
for element in ex0_demo_input:
    result.extend([s.strip() for s in re.split(r'\.|\?|\!', element)])
    result = [s for s in result if s]
result

['This is a phrase; this, too, is a phrase',
 'But this is another sentence',
 'Hark',
 'Come what may    <-- save those spaces, but not these -->',
 'What did you say',
 'Split into 3 (even without a space)',
 'Okie dokie']

In [29]:
clustering = np.array([ 8, 5, 5, 8, 6, 7,  4, 1, 8, 7, 5,  8, 8])
y = np.array([-1, 5, 6, 9, 6, 7, -1, 1, -1, 7, 6, -1, 3])
k = 10
z = np.array([-1] * k)

In [32]:
#from collections import Counter
for i in set(clustering):
    y_indices = np.where(clustering == i)[0]
    y_take = np.take(y, y_indices)
    y_filtered = np.extract(y_take != -1, y_take)
    if y_filtered.size:
        counts = np.bincount(y_filtered)
        z[i] = np.argmax(counts)
        #most_common = Counter(y_filtered).most_common()
        #if most_common[0][1] == most_common[-1][1]:
        #    z[i] = min(most_common)[0]
        #else:
        #    z[i] = most_common[0][0]
z

array([-1,  1, -1, -1, -1,  6,  6,  7,  3, -1])

In [21]:
Y = np.array([4, 2, 1, 1, 3, 2, 4, 2, 2, 2, 4])
y = np.array([2, 3, 5, 6])

In [23]:
p = Y[y]
p

array([1, 1, 2, 4])

In [25]:
counts = np.bincount(p)
counts

array([0, 2, 1, 0, 1], dtype=int64)

In [26]:
np.argmax(counts)

1

In [16]:
import numpy as np
X = np.array([
    [5, 5, 4],
    [8, 1, 8],
    [0, 1, 5],
    [0, 3, 1],
    [6, 2, 5]
])

w = np.array([
    [8, 5, 1],
    [7, 8, 6]
])

x = np.array(
    [8, 5, 1]
)

In [8]:
X - w[:,np.newaxis]

array([[[-3,  0,  3],
        [ 0, -4,  7],
        [-8, -4,  4],
        [-8, -2,  0],
        [-2, -3,  4]],

       [[-2, -3, -2],
        [ 1, -7,  2],
        [-7, -7, -1],
        [-7, -5, -5],
        [-1, -6, -1]]])

In [9]:
X[:,np.newaxis] - w

array([[[-3,  0,  3],
        [-2, -3, -2]],

       [[ 0, -4,  7],
        [ 1, -7,  2]],

       [[-8, -4,  4],
        [-7, -7, -1]],

       [[-8, -2,  0],
        [-7, -5, -5]],

       [[-2, -3,  4],
        [-1, -6, -1]]])

In [17]:
np.sum(X - x, axis = 1)

array([  0,   3,  -8, -10,  -1])

In [18]:
np.sqrt(np.sum((X - x)**2, axis=1))

array([4.24264069, 8.06225775, 9.79795897, 8.24621125, 5.38516481])

In [20]:
np.linalg.norm(X - x, axis = 1)

array([4.24264069, 8.06225775, 9.79795897, 8.24621125, 5.38516481])

In [19]:
np.argsort(np.sqrt(np.sum((X - x)**2, axis=1)))[0:2]

array([0, 4], dtype=int64)

In [14]:
l = [(1, 2), (4, 3), (7, 8), (10, 11)]

In [3]:
import operator

In [16]:
x = 0

In [20]:
[operator.iadd(x + a + b, x + a + b) for a, b in l]

[6, 14, 30, 42]

In [11]:
f = operator.itemgetter(1, 3)

In [12]:
f(l)

((4, 3), (10, 11))

In [ ]:
res = []
aux = set()
for x in nums:
  if x not in aux:
    res.append(x)
    aux.add(x)

In [47]:
import numpy as np
A = np.array([[0, 1, 0, 1, 0, 1],
              [1, 0, 0, 1, 0, 0],
              [0, 0, 0, 1, 0, 0],
              [1, 1, 1, 0, 1, 1],
              [0, 0, 0, 1, 0, 0],
              [1, 0, 0, 1, 0, 0]], dtype=int)

In [53]:
(np.multiply(A.dot(A), A).sum(axis = 1)/6).astype(int)

array([0, 0, 0, 0, 0, 0])

In [82]:
I = [0, 1, 2, 3, 2, 3]

In [83]:
J = [1, 0, 3, 2, 3, 2]

In [60]:
from scipy.sparse import coo_matrix

In [84]:
n = max(I) + 1

In [85]:
V = np.ones(len(I), dtype=int)
V

array([1, 1, 1, 1, 1, 1])

In [86]:
A = coo_matrix((V, (I, J)), shape=(n, n))
print(A)

  (0, 1)	1
  (1, 0)	1
  (2, 3)	1
  (3, 2)	1
  (2, 3)	1
  (3, 2)	1


In [87]:
A.sum_duplicates()
print(A)

  (1, 0)	1
  (0, 1)	1
  (3, 2)	2
  (2, 3)	2


In [88]:
A = (A > 0).astype(int).todense()
print(A)

[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [69]:
C = A.dot(A) * A
print(C.sum(axis = 1)/6)

[[0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]]


In [10]:
import numpy as np

In [13]:
A = np.zeros((2, 2))
A[1,1] = 1

In [14]:
A

array([[0., 0.],
       [0., 1.]])

In [7]:
from itertools import groupby

In [8]:
l = [[2,5], [2, 5], [3,4]]

In [9]:
[k for k, g in groupby(l)]

[[2, 5], [3, 4]]

In [56]:
s = [1, 2, 3, 4]
from itertools import permutations, combinations


In [55]:
{t : 1 for t in list(permutations(s, 2))}

{(1, 2): 1,
 (1, 3): 1,
 (1, 4): 1,
 (2, 1): 1,
 (2, 3): 1,
 (2, 4): 1,
 (3, 1): 1,
 (3, 2): 1,
 (3, 4): 1,
 (4, 1): 1,
 (4, 2): 1,
 (4, 3): 1}

In [57]:
{t : 1 for t in list(combinations(s, 2))}

{(1, 2): 1, (1, 3): 1, (1, 4): 1, (2, 3): 1, (2, 4): 1, (3, 4): 1}

In [156]:
inputData = ''

In [147]:
import math

In [157]:
'\n'.join(
    [
        str(int(math.log(int(line), 2).is_integer())) 
        for line in inputData.splitlines()[1:]
    ]
)

''

In [ ]:
def codeHere():
    lines = [int(line) for line in inputData.splitlines()]
    bool_vals = [(x != 0) and (x & (x - 1) == 0) for x in lines[1:]]
    output = list(map(int, bool_vals))
    output = [str(x) for x in output]
    return '\n'.join(output)

In [107]:
import numpy as np

In [133]:
v = np.asarray([True, False, True, False])

In [136]:
# if you don't specify the replacements
# then you get back the indices of `True` values
np.where(v)

(array([0, 2], dtype=int64),)

In [138]:
# `v` should be a `numpy` array
np.where(v, 4, 5)

array([4, 5, 4, 5])

In [106]:
[xv if c else yv
 for c, xv, yv in zip(condition, x, y)]

NameError: name 'condition' is not defined

In [102]:
s = 'We analyzed found the issue in Garbage Collection which crashed the JVM.\r\n\r\n\xa0\r\n\r\n\xa0\r\n\r\n_Stack: [0x00007f0b58ff1000,0x00007f0b590f1000],\xa0 sp=0x00007f0b590ef120,\xa0 free space=1016k_\r\n\r\n_Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)_\r\n\r\n_V\xa0 [libjvm.so+0x8b9e4f]\xa0 MethodData::clean_extra_data(BoolObjectClosure)+0x1cf_\r\n\r\n_V\xa0 [libjvm.so+0x63c582]\xa0 '

In [93]:
import re

In [105]:
re.sub(r'(\\r)|(\\n)|(\\xa0)', '', s)

'We analyzed found the issue in Garbage Collection which crashed the JVM._Stack: [0x00007f0b58ff1000,0x00007f0b590f1000], sp=0x00007f0b590ef120, free space=1016k__Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)__V [libjvm.so+0x8b9e4f] MethodData::clean_extra_data(BoolObjectClosure)+0x1cf__V [libjvm.so+0x63c582] '

In [74]:
dic = {
    'A' : ['b', 'a', 'a', 'd', 'd', 'c'],
    'B' : [3, 1, 1, 4, 1, 4],
    'C' : [3, 2, 2, 4, 2, 5],
    'D' : [4, 1, 1, 1, 1, 6]
}
df = pd.DataFrame(dic)
df

A  B  C  D
0  b  3  3  4
1  a  1  2  1
2  a  1  2  1
3  d  4  4  1
4  d  1  2  1
5  c  4  5  6

In [91]:
df = (
    df
        .assign(A = lambda x: pd.Categorical(x['A'], categories = ['b', 'd', 'c', 'a'], ordered = True))
        .sort_values('A')
)

A  B  C  D
0  b  3  3  4
3  d  4  4  1
4  d  1  2  1
5  c  4  5  6
1  a  1  2  1
2  a  1  2  1

In [56]:
dic = {
    'a': {
        'b': [1, 2], 
        'c': [3, 4]
    }, 
    'A': {
        'B': [10, 20], 
        'C': [30, 40]
    }
}
s = (
    pd.DataFrame(dic)
        .stack()
        .explode()
        .reset_index()
        .filter(['level_1', 'level_0', 0])
        .rename(columns = {'level_1' : 'col_1', 'level_0' : 'col_2', 0 : 'col_3'})
)
s

col_1 col_2 col_3
0     a     b     1
1     a     b     2
2     a     c     3
3     a     c     4
4     A     B    10
5     A     B    20
6     A     C    30
7     A     C    40

In [32]:
import pandas as pd


def my_function(df):
    kwargs = {
        "quantity": df.apply(lambda x: -x["quantity"] if "SELL" in str(x["action"]) else x["quantity"], axis = 1),
        "price (usd)": df.apply(lambda x: 0 if "SELL" in str(x["action"]) else x["price (usd)"], axis = 1),
    }
    return df.assign(**kwargs)


input_df = pd.DataFrame({"product": ["APPLE", "APPLE", "BANANA"],
                         "action": ["  SELL  ", "  BUY  ", "  SELL  "],
                         "quantity": [1, 2, 3],
                         "price (usd)": [3, 5, 8],
                         })

result_df = my_function(input_df)
result_df

product    action  quantity  price (usd)
0   APPLE    SELL          -1            0
1   APPLE     BUY           2            5
2  BANANA    SELL          -3            0

In [8]:
expected_df = pd.DataFrame({"product": ["APPLE", "APPLE", "BANANA"],
                            "action": ["  SELL  ", "  BUY  ", "  SELL  "],
                            "quantity": [-1, 2, -3],
                            "price (usd)": [0, 5, 0],
                            })
expected_df

product    action  quantity  price (usd)
0   APPLE    SELL          -1            0
1   APPLE     BUY           2            5
2  BANANA    SELL          -3            0

In [5]:
    numbers = [25, 24, 26, 45, 25, 23, 50, 51]
    count = len(numbers)
    filtered = [num for num in numbers if 25 <= num <= 50]
    count = len(numbers) - len(filtered)
    filtered

[25, 26, 45, 25, 50]

If a polynomial function has integer coefficients, then every rational zero will have the form

$$
\frac{p}{q}
$$

where `p` is a factor of the constant and `q` is a factor of the leading coefficient.

In [139]:
import numpy as np
A = np.array ([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]
              ], dtype=float)

print ("A[:, :] ==\n", A)
print ("\na0 := A[:, 0] ==\n", A[:, 0])
print ("\na1 := A[:, 2:3] == \n", A[:, 2])

print ("\nAdd columns 0 and 2?")
a0 = A[:, 0]
a1 = A[:, 2]
print (a0 + a1)

A[:, :] ==
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

a0 := A[:, 0] ==
 [1. 4. 7.]

a1 := A[:, 2:3] == 
 [3. 6. 9.]

Add columns 0 and 2?
[ 4. 10. 16.]


In [69]:
import numpy as np

In [74]:
np.convolve([2, 3, 5], [7, 6, 4])

array([14, 33, 61, 42, 20])

In [77]:
np.convolve([2, 3, 5], [7, 6, 4], 'same')

array([33, 61, 42])

In [126]:
X = np.array([[1,1,0], [1,0,0], [0,0,1]])

In [131]:
np.ones(X.shape) * -1

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [133]:
X

array([[1, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [120]:
kernel = np.ones(X.shape) * -1

In [135]:
from scipy.signal import convolve2d
convolve2d(X, kernel, 'same')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
class TreeNode:
    def __init__(self, x):
        self.val = x
        self.left = None
        self.right = None

In [30]:
def insertLevelOrder(arr, root, i, n): 
      
    # Base case for recursion  
    if i < n: 
        temp = TreeNode(arr[i])  
        root = temp  
  
        # insert left child  
        root.left = insertLevelOrder(arr, root.left, 
                                     2 * i + 1, n)  
  
        # insert right child  
        root.right = insertLevelOrder(arr, root.right, 
                                      2 * i + 2, n) 
    return root

In [39]:
def inOrder(root): 
    if root != None: 
        inOrder(root.left)  
        print(root.val,end=" ")  
        inOrder(root.right) 
        
if __name__ == '__main__': 
    arr = [1, 2, 3, 4, 5, 6, 6, 6, 6] 
    n = len(arr) 
    root = None
    root = insertLevelOrder(arr, root, 0, n)  
    inOrder(root)

6 4 6 2 5 1 6 3 6 

In [63]:
stk = [root]

In [64]:
node = stk.pop()

In [68]:
inOrder(node)

6 4 6 2 5 1 6 3 6 

In [56]:
node = stk.pop()

IndexError: pop from empty list

In [9]:
J, S = "aA", "aAAbbbb"

In [37]:
print(root.left)

In [ ]:
class Solution:
    def numJewelsInStones(self, J: str, S: str) -> int:
        count = 0
        for j in J:
            for s in S:
                if s == j:
                    count += 1
        return count

In [18]:
for c in S:
    print(c)

a
A
A
b
b
b
b


In [17]:
set(S)

{'A', 'a', 'b'}

In [16]:
set(J)

{'A', 'a'}

In [12]:
sum([1 for c in S if c in J])

3

In [14]:
Jli = list(set(list(J)))
count = 0
for j in Jli:
	count += S.count(j)
count

3

In [15]:
sum([S.count(i) for i in J])

3

In [1]:
num = 14

In [2]:
sum([int(d) + 1 for d in bin(num)[2:]]) - 1

6

In [4]:
bin(num)[2:]

'1110'

In [8]:
len(b := bin(num)[2:]) + b.count('1') - 1

SyntaxError: invalid syntax (<ipython-input-8-e57fad0e8c34>, line 1)

In [113]:
myList = [1, 1, 2, 2, 2, 3]
output = {}

for item in myList:
    if item not in output:
        output[item] = 0
    output[item] += 1

output

{1: 2, 2: 3, 3: 1}

In [19]:
from string import ascii_letters, digits
import timeit

In [20]:
words = list(ascii_letters+digits)*10**5
len(words)

6200000

In [16]:
start_time = timeit.default_timer()
from collections import defaultdict
d = defaultdict(int)
for w in words: d[w] += 1
elapsed = timeit.default_timer() - start_time
elapsed

0.6867543999999839

In [ ]:

%timeit words
d = {i:words.count(i) for i in words}

20.8 ns ± 1.03 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [ ]:
mycode = ''' 
d = defaultdict(int)
for w in words: d[w] += 1
'''

In [91]:
mycode = ''' 
#words = list(digits)*10**5

answers = [0, 2, 2, 2]

d = Counter(answers)
'''

In [92]:
mysetup = '''
from collections import Counter
#from string import ascii_letters, digits
'''

In [107]:
timeit.timeit(setup = mysetup, stmt = mycode, number = 7)

3.199999991920777e-05

In [9]:
from collections import Counter
%timeit words
d = Counter(words)

19.4 ns ± 1 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [106]:
answers = [0, 2, 2, 2]
%timeit answers
from collections import Counter

d = Counter(answers)

21.7 ns ± 1.45 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [ ]:
words=[0, 2, 2, 2]
{i:words.count(i) for i in words}

In [ ]:
start_time = timeit.default_timer()
# code you want to evaluate
elapsed = timeit.default_timer() - start_time

In [ ]:
from itertools import groupby as gb
from math import ceil
answers = [1,0,1,0,0]  
lst = [(len(list(v)), g) for g, v in gb(sorted(answers))]

[(len(list(v)), g) for g, v in gb(sorted(answers))]

In [ ]:
[ceil(t[0]/(t[1] + 1)) * (t[1] + 1) for t in lst]

In [ ]:
from collections import Counter
Counter(answers)

In [ ]:
sum([ceil(v/(k + 1)) * (k + 1) for k, v in Counter(answers).items()])

In [ ]:
[len(answers) + 1 for g, v in gb(sorted(answers))]

In [ ]:
# For every grouping of K rabbits, where K is the total number of rabbits that had the 
# same answer, we can deduce that the minimum number of rabbits is equal to Math.ceil(K/(answer + 1)) * (answer + 1).

In [ ]:
from collections import Counter
answers = [0,0,1,1,1]
l1 = [list(v) for g, v in gb(sorted(answers))]
c = Counter(answers)
c

In [ ]:
sum((c[i] + i) / (i + 1) * (i + 1) for i in c)

In [ ]:
[divmod(len(l), 2) for l in l1]

In [ ]:
answers = [1,0,1,0,0]
#sum(len(answers)) + divmod(len(answers), 2)[1]
#divmod(len(answers), 2)[1]

In [ ]:
from itertools import groupby as gb
l = list(gb(answers, key = lambda k: k))
#list(list(gb(answers))[0][1])

list(l[0][1])

In [ ]:
[(t[0], list(t[1])) for t in l]

In [ ]:
import pandas as pd
df=[['7','4','5','',''],["","","",'7','4'],['9','4','7','8','4'],["","","",'7','5'],['4','8','5','4','6'],['4','9','41','74','20'],['4','Super','yes','0','9']]
df=pd.DataFrame(df)
df.astype('str')
df.iloc[1 : 4,:].apply(lambda x : ''.join(x)).to_frame().transpose()#.reset_index()#.pivot(index = 'index', columns = 'index', values = '0')

In [ ]:


# this is an important step because we need a column to groupby
#df['gb'] = 'gb'

start_end = [[1,3],[4,5]]

#df.columns = ['0', '1', '2', '3', '4', 'gb']

new_df = pd.DataFrame()

for l in start_end:
    
    #temp_df = df.iloc[l[0] : l[1] + 1,:].groupby(['gb']).agg(lambda x : ''.join(x)).reset_index(drop = True)
    temp_df = df.iloc[l[0] : l[1] + 1,:].apply(lambda x : ''.join(x)).to_frame().transpose()
    
    new_df = pd.concat([new_df, temp_df], ignore_index = True)

new_df

In [ ]:
start_end = [[1,3],[4,5]]

new_df = pd.DataFrame()

for l in start_end:
    
    temp_df = df.iloc[l[0] : l[1] + 1,:].apply(lambda x : ''.join(x)).to_frame().transpose()
    
    new_df = pd.concat([new_df, temp_df], ignore_index = True)

new_df

In [ ]:
from itertools import product
{
  sum(x ** 2 for x in xs) : xs
  for xs in product(range(7), repeat=3)
  if sum(x ** 2 for x in xs) % 8 in {3, 4, 0}
}

In [ ]:
[
    (x, f(x) , g(x)) 
    for (x, f(x), g(x)) in (
        (x, f(x), g(fx))
        for (x, f(x)) in (
            (x, f(x)) 
            for x in bigList
        )
        if f(x) < p
    )
    if g(x) < q
]

In [ ]:
def xs(x, y):
    return x - y

iter1 = [1, 2, 3]
iter2 = [4, 6, 8, 9]

iter(list(map(xs, iter1, iter2)))

In [ ]:
import re
pattern = r'base=\"(?P<groupname>[0-9]{1,10})\"'
s = '<div aim="" base="1005260" class="item card cb23 eb02 rb3 d1" ele="2" imgur="kMBzbLb" quantity="" release="" res="1005260" type="1"><div class="content"></div><a class="ab" hash="" href="/cards/1005260-vegito-peerless-combination" title="Peerless Combination - Vegito"><table><tr><td class="dokkan"></td><td class="element"></td></tr><tr><td class="rarity"><i>ssr</i></td><td class="lock off"><i class="material-icons off"></i><i class="material-icons on"></i></td></tr></table></a><div class="dv">11921</div></div>'
int(re.search(pattern, s).group('groupname'))
